
// DASHBOARD
export const FETCH_REPORT_BY_USER = 'FETCH_REPORT_BY_USER'

//USERS

export const FETCH_USERS_BEGIN = 'FETCH_USERS_BEGIN'
export const RECEIVE_USERS = 'RECEIVE_USERS'
export const FETCH_SINGLE_USER = 'FETCH_SINGLE_USER'
export const ADD_USER = 'ADD_USER'
export const REMOVE_USER = 'REMOVE_USER'
